### ISSUE TITLE
Error HttpRequestMessage

### ISSUE THREAD

**Issue by igorcb123** [elGuille-info/gcnl_AnalizarFrases#1]
Me da este error al ejecutar cuando se quiere llamar a AnnotateText

Error starting gRPC call. HttpRequestException: Unable to get subchannel from HttpRequestMessage. (10.1.12.120:8082) InvalidOperationException: Unable to get subchannel from HttpRequestMessage.", DebugException="System.Net.Http.HttpRequestException: Unable to get subchannel from HttpRequestMessage. (10.1.12.120:8082)
 ---> System.InvalidOperationException: Unable to get subchannel from HttpRequestMessage.
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.OnConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

**Comment by elGuille-info** [comment]
Buenas, déjame que le eche un vistazo a mis notas y la documentación ya que ahora no me acuerdo de estas APIs de Google 😊
Después más tarde te digo algo si es que puede ser por algo indicado en las apis.
Gracias.

Dime también desde dónde estás usando la clase Frases, si es desde uno de los ejemplos que he puesto (cuál, el de consola o el de MAUI (en este caso desde qué tipo de app).
Gracias.
